### ISSUE TITLE
Remote cache issues: `IOException: Could not parse Deps.Dependencies message from proto`

### ISSUE THREAD

**Issue by sgammon** [buildbuddy-io/buildbuddy#1955]
Hey beloved Buildbuddy authors,

When we are building in CI (Linux -- Ubuntu LTS, 20.x), we get the following error, but only when remote caching is turned on with Buildbuddy:

```
java.io.IOException: error reading deps artifact: bazel-out/k8-opt-exec-2B5CBBC6/bin/external/io_grpc_grpc_java/context/libcontext-hjar.jdeps
	at com.google.devtools.build.buildjar.javac.plugins.dependency.DependencyModule.collectDependenciesFromArtifact(DependencyModule.java:290)
	at com.google.devtools.build.buildjar.javac.plugins.dependency.DependencyModule.computeStrictClasspath(DependencyModule.java:256)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:52)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:110)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:118)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:101)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:81)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:65)
Caused by: java.io.IOException: Could not parse Deps.Dependencies message from proto.
	at com.google.devtools.build.buildjar.javac.plugins.dependency.DependencyModule.collectDependenciesFromArtifact(DependencyModule.java:280)
	... 7 more
```

This particular set of `jdeps` doesn't seem special, and we've seen this error before in our build logs. We're running on Bazel latest (`5.1.1` at time of writing)

**Comment by siggisim** [comment]
Hey Sam! 

Are you able to reproduce this with older versions of Bazel (say 5.0)?

Do you have `--remote_download_minimal` or `--remote_download_toplevel` set? Are you able to reproduce this without setting those flags?

Does setting either (or both) of these bazel flags solve the issue?
```
--experimental_inmemory_jdeps_files
--experimental_inmemory_dotd_files
```

Sorry for the barrage of questions, trying to narrow in on what the issue could be. Seems like jdeps can be sensitive to these flags. Looks like Keith is working on making this Bazel's default behavior: https://github.com/bazelbuild/bazel/pull/15204

**Comment by sgammon** [comment]
@siggisim good question and i'll push some changes that adjust those flags to see if they give any hints. in the meantime, though, i've now witnessed this using the regular Bazel disk cache, so i think it's safe to say it's not buildbuddy-related 😀 

thank you so much for the quick response! i'll file this with the bazel main repo and link this issue if i can find a reliable repro.
