### ISSUE TITLE
Windows builds constantly failing with IOException: connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by avdv** [buildbuddy-io/buildbuddy#4467]
We are using Bazel 6.2.0 currently, but the issue existed before (I tried to follow suggestions in https://github.com/buildbuddy-io/buildbuddy/issues/992 but no dice).

The issue only happens for the Windows builds, Linux and Darwin are fine.

```
ERROR: The Build Event Protocol upload failed: Not retrying publishBuildEvents, no more attempts left: status='Status{code=UNAVAILABLE, description=io exception, cause=java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
}' UNAVAILABLE: An existing connection was forcibly closed by the remote host UNAVAILABLE: An existing connection was forcibly closed by the remote host
INFO: Build completed successfully, 511 total actions
Error: Process completed with exit code 38.
```
CI runs: [1](https://github.com/tweag/rules_haskell/actions/runs/5738410548/job/15564769755#step:7:673) ([bb](https://app.buildbuddy.io/invocation/6f2da6e1-23b5-4ba8-bb79-bc5e7a9860dd)), [2](https://github.com/tweag/rules_haskell/actions/runs/5738410548/job/15564770359#step:8:2429) ([bb](https://app.buildbuddy.io/invocation/897e763b-eef6-4bc1-9970-36018b01efed)), [3](https://github.com/tweag/rules_haskell/actions/runs/5738410548/job/15564770160#step:8:2453) ([bb](https://app.buildbuddy.io/invocation/cb648c22-d761-4ba9-b494-89d14862af5b))

Note, we have 4 jobs in the workflow running on Windows, and one of them succeeded: https://github.com/tweag/rules_haskell/actions/runs/5738410548/job/15564769980?pr=1925

The successful job took a bit over one hour, the failing jobs took >5 hours. Could this be just some sort of timeout?

We are using:
```
--bes_upload_mode=wait_for_upload_complete
--bes_timeout=60s
```
Should we try something else? Or tune different parameters? Thank you for any suggestions!

**Comment by siggisim** [comment]
@sluongng any chance you're able to reproduce this on Windows? 

This kind of feels like an error that Bazel would handle gracefully / retry on Linux ([this](https://stackoverflow.com/questions/2582036/an-existing-connection-was-forcibly-closed-by-the-remote-host) suggests that this is the windows error message for a RST stream).

I believe our servers send an RST stream when they're restarting (and the 3 errors linked are around this time of our release yesterday when all of the apps are started, which happened around noon PST).

The question for me is why isn't Bazel able to successfully retry the BES stream on Windows like it seems to be able to on Linux / Mac (otherwise we could never restart our servers / perform releases).

**Comment by sluongng** [comment]
I have not seen this before while I was trying to build BuildBuddy on Windows 🤔 

Gona reach out to Tweag folks on Slack to see if I could reproduce with rules_haskell or not... though I doubt that this is specific to a repo, there might be some flags/options specific to rules_haskell CI (or their GitHub Action Runner) that could affect this.

**Comment by siggisim** [comment]
Seems like it happened during a release, you could try running a Windows build against a local server and restarting it mid build.

**Comment by sluongng** [comment]
Slightly hard since our server does not build on Windows 😅 
But I took that as a challenge: I set up a personal VPN on my Windows VM and ran `//server` on my MacBook.

Tried to stop and restart server on my MacBook 2 times mid-build but could not reproduce the issue 🤔

**Comment by sluongng** [comment]
I tried a bunch of approaches and could not replicate the exact error.

@avdv It would be helpful if you could help capture the java log in `$(bazel info output-base)/java.log*`, specifically the logs from `BuildEventServiceUploader` would be pretty beneficial. I want to check the timing of the `Retrying stream` log and its reasons.

It's likely that the 5 hours build duration overlapping with our weekly release time frame was the root cause of this: our old server received the stream -> was interrupted for upgrade -> Bazel retried to another server that would also get interrupted later. If this is indeed the case, bumping `--experimental_build_event_upload_max_retries=4` to a higher number would be a good solution.

**Comment by avdv** [comment]
Thank you!

> It would be helpful if you could help capture the java log in `$(bazel info output-base)/java.log*`, specifically the logs from `BuildEventServiceUploader` would be pretty beneficial. I want to check the timing of the `Retrying stream` log and its reasons.

I'll try to reproduce and attach the files.

**Comment by sluongng** [comment]
discussed with @avdv on Slack and tested it myself in https://github.com/sluongng/rules_haskell/actions/runs/5785750975/job/15678998276 https://app.buildbuddy.io/invocation/c912e3eb-c949-4872-9246-47a743b7425d

It seems that the issue is unrelated to our weekly release. I could not reproduce it on AWS EC2 Windows VM, but it seems like the Github Action's managed runner (on Azure) could be easily reproduced.

**Comment by siggisim** [comment]
One thing I've noticed is that the Github action runners on Linux seem to have pretty flaky networking, and that setting this kernel param seems to help:
```
sudo sysctl -w net.ipv4.tcp_keepalive_time=60
```

I wonder if there is an equivalent for Windows. Based on this it seems the default is 2 hours and it can be tweaked: https://serverfault.com/a/735768

**Comment by avdv** [comment]
I did set the `KeepAliveTime` registry entry to [300000 milliseconds = 5 mins](https://github.com/avdv/rules_haskell/blob/9b48bd6991f3e3b208260eb46bffddf6f87a07a6/.github/workflows/workflow.yaml#L109), but that did not help. Yet it seems to happen at a steady rate once every 5mins now...
```
230809 06:29:01.478:I 20 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceModule.logIds] Streaming Build Event Protocol to 'grpcs://remote.buildbuddy.io' wi│
230809 06:29:21.604:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=2           │
230809 06:34:05.272:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 06:34:06.272:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=134         │
230809 06:45:19.297:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 06:45:20.902:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=318         │
230809 06:49:50.790:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 06:49:53.353:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=318         │
230809 06:54:22.370:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 06:54:26.471:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=318         │
230809 06:58:55.971:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 06:59:02.538:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=318         │
230809 07:03:31.893:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:03:42.384:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=318         │
230809 07:10:15.104:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:10:31.887:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=386         │
230809 07:19:28.817:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:19:55.674:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=389         │
230809 07:24:26.380:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:25:09.346:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=389         │
230809 07:29:39.393:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:30:48.115:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=389         │
230809 07:35:17.988:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:37:07.943:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=390         │
230809 07:41:37.300:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:44:33.241:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=390         │
230809 07:50:15.981:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Retrying stream: status='Status{code=UNAVAILABLE, de│
230809 07:54:57.464:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Starting publishBuildEvents: eventQueue=445         │
230809 07:54:57.620:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] BES uploader is half-closed                         │
230809 07:54:58.451:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] publishBuildEvents was successful                   │
230809 07:54:58.451:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] About to cancel all local file uploads              │
230809 07:54:58.451:I 232 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Spent 0 milliseconds doing local file upload cancell│
230809 07:54:58.621:I 20 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceModule.waitForBuildEventTransportsToClose] Spent 21048 milliseconds doing waiting │
```

Setting [`--experimental_build_event_upload_max_retries=256`](https://github.com/avdv/rules_haskell/blob/9b48bd6991f3e3b208260eb46bffddf6f87a07a6/.bazelrc.common#L67) did remedy the issue although I saw "The Build Event Protocol upload timed out." in one [job](https://github.com/tweag/rules_haskell/actions/runs/5805659118/job/15737115605?pr=1931) instead.

**Comment by sluongng** [comment]
https://www.buildbuddy.io/docs/troubleshooting-slow-upload#the-build-event-protocol-upload-timed-out

We do recommend setting the BES timeout value to 600s here. I think it should help with cases like yours, but it would be better to know where in the network stack did the failure occur 🤔

**Comment by avdv** [comment]
Thank you @sluongng, but seems like it did not help: https://github.com/tweag/rules_haskell/actions/runs/5834070440/job/15838104954?pr=1935

I'll retry and try to get a log file.

**Comment by sluongng** [comment]
We have recently helped a few customers troubleshoot their AWS network connectivity. Folks who connect to BuildBuddy through a NAT Gateway would often be subjected to the gateway's TCP timeout, especially when it comes to a long-running grpc stream.

It's unknown how Github is setting up the managed Windows runners, but I guess that it's also subjected to similar limitations.
https://learn.microsoft.com/en-us/azure/nat-gateway/troubleshoot-nat-connectivity#tcp-idle-timeout-timers-set-higher-than-the-default-value

On Bazel side, there are [--grpc_keepalive_time](https://bazel.build/reference/command-line-reference#flag--grpc_keepalive_time) and [--grpc_keepalive_timeout](https://bazel.build/reference/command-line-reference#flag--grpc_keepalive_timeout) flags that might help with these behavior.

There is also [--experimental_remote_execution_keepalive](https://bazel.build/reference/command-line-reference#flag--experimental_remote_execution_keepalive) but I don't think RBE is relevant here.

Also here is how you can tune the setting on Linux's sysctl https://www.buildbuddy.io/docs/troubleshooting-rbe#warning-remote-cache-unavailable-io-exception. It seems like you can achieve a similar effect on Windows https://serverfault.com/questions/735515/tcp-timeout-for-established-connections-in-windows. However, since we are discussing Github-managed runners, I think these are less relevant.
