### ISSUE TITLE
An error occurred during the fetch of repository 'go_googleapis'

### ISSUE THREAD

**Issue by konste** [buildbuddy-io/buildbuddy#6]
I am trying to follow Getting Started guide for on prem and the build fails with the errors:
```ubuntu@bazel-server:~/Desktop/buildbuddy$ bazel run -c opt server:buildbuddy
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/2b5c8107-852d-4f7c-a720-45615d2b3210
INFO: Call stack for the definition of repository 'go_googleapis' which is a http_archive (rule definition at /home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/io_bazel_rules_go/go/private/repositories.bzl:241:9
 - /home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/io_bazel_rules_go/go/private/repositories.bzl:209:5
 - /home/ubuntu/Desktop/buildbuddy/WORKSPACE:29:1
ERROR: An error occurred during the fetch of repository 'go_googleapis':
   Traceback (most recent call last):
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
		patch(ctx)
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
		fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patching file BUILD.bazel
patching file WORKSPACE
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file WORKSPACE.rej
patching file google/BUILD.bazel
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/org_golang_google_grpc/status/BUILD.bazel:3:1: @org_golang_google_grpc//status:go_default_library depends on @go_googleapis//google/rpc:status_go_proto in repository @go_googleapis which failed to fetch. no such package '@go_googleapis//google/rpc': Traceback (most recent call last):
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
		patch(ctx)
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
		fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patching file BUILD.bazel
patching file WORKSPACE
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file WORKSPACE.rej
patching file google/BUILD.bazel
ERROR: Analysis of target '//server:buildbuddy' failed; build aborted: no such package '@go_googleapis//google/rpc': Traceback (most recent call last):
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/bazel_tools/tools/build_defs/repo/http.bzl", line 84
		patch(ctx)
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/d66ea702277a82b20058abe99a1364a3/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 148, in patch
		fail(<1 more arguments>)
Error applying patch @io_bazel_rules_go//third_party:go_googleapis-directives.patch:
patching file BUILD.bazel
patching file WORKSPACE
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file WORKSPACE.rej
patching file google/BUILD.bazel
INFO: Elapsed time: 67.262s
INFO: 0 processes.
ERROR: Build failed. Not running target
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/2b5c8107-852d-4f7c-a720-45615d2b3210
FAILED: Build did NOT complete successfully (220 packages loaded, 14517 target\
s configured)
    Fetching @in_gopkg_yaml_v2; fetching 20s
    Fetching @org_golang_google_api; fetching 20s
    Fetching @com_github_mattn_go_sqlite3; fetching
ubuntu@bazel-server:~/Desktop/buildbuddy$ ^C
```

**Comment by siggisim** [comment]
Hey Konstantin - I've seen this error when using Bazel version 2.2.0. We're currently pinned to Bazel version 2.1.0 per our [.bazelversion](https://github.com/buildbuddy-io/buildbuddy/blob/master/.bazelversion) file:

If you use a Bazel launcher like [bazelisk](https://github.com/bazelbuild/bazelisk) it should respect that .bazelversion file. We should be more clear about this in our documentation! 

Will work on getting those io_bazel_rules_go version updated to support the latest version. Will close this issue once we've updated documentation to mention bazelisk, and we've bumped the pinned Bazel version to 2.2.0.

**Comment by konste** [comment]
@siggisim Thanks a lot for the prompt response! Indeed with Bazel 2.1.0 it compiles.

**Comment by konste** [comment]
It compiles successfully, but then I get this:
```2020/03/12 03:35:11 Directory '/tmp/buildbuddy' did not exist; creating it.

(external/com_github_jinzhu_gorm/scope.go:1047) 
[2020-03-12 03:35:11]  [7.27ms]  CREATE TABLE "Invocations" ("created_at_usec" bigint,"updated_at_usec" bigint,"invocation_id" varchar(255),"success" bool,"user" varchar(255),"duration_usec" bigint,"host" varchar(255),"command" varchar(255),"pattern" varchar(255),"action_count" bigint,"blob_id" varchar(255),"invocation_status" bigint , PRIMARY KEY ("invocation_id"))  
[0 rows affected or returned ] 

(external/com_github_jinzhu_gorm/scope.go:1047) 
[2020-03-12 03:35:11]  [3.39ms]  CREATE INDEX user_index ON "Invocations"("user")   
[0 rows affected or returned ] 
```
What is it I am missing?

**Comment by siggisim** [comment]
Those should just be harmless log statements coming from the ORM. If you're seeing those - the server should be up and running correctly. 

You should be able to point your `--bes_results_url=` and  `--bes_backend=` flags at it now and view results from the build.

**Comment by konste** [comment]
Apparently it run out of disk space, which I promptly fixed. Now it starts:
gRPC listening on http://0.0.0.0:1985
HTTP listening on http://0.0.0.0:8080
but the port 8080 is already occupied!

Two problems with that:
1. I edited config/buildbuddy.local.yaml to include the line `build_buddy_url: "http://localhost:1984"` (instead of 8080), but how to make it restart and re-read that config?
2. Where gRPC port is configured?

**Comment by siggisim** [comment]
Hey @konste - you can edit http and grpc ports here, either inline or by passing in these flags:
https://github.com/buildbuddy-io/buildbuddy/blob/master/server/libmain.go#L27

**Comment by konste** [comment]
And how do I restart the server in order for the new values to take effect?

**Comment by konste** [comment]
This issue became too randomized, so as the original question is fully resolved I am going to close this issue and open another one to cover specifically the information not available in the current docs.
